export const mockCandidates = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice@example.com",
    role: "Senior Frontend Engineer",
    experience: "5 years",
    status: "Scheduled",
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob@example.com",
    role: "Product Manager",
    experience: "7 years",
    status: "Shortlisted",
  },
  {
    id: 3,
    name: "Charlie Davis",
    email: "charlie@example.com",
    role: "UI/UX Designer",
    experience: "3 years",
    status: "Pending",
  },
  {
    id: 4,
    name: "Diana Prince",
    email: "diana@example.com",
    role: "Senior Frontend Engineer",
    experience: "6 years",
    status: "Rejected",
  },
  {
    id: 5,
    name: "Ethan Hunt",
    email: "ethan@example.com",
    role: "Backend Developer",
    experience: "4 years",
    status: "In Progress",
  },
  {
    id: 6,
    name: "Fiona Green",
    email: "fiona@example.com",
    role: "DevOps Engineer",
    experience: "5 years",
    status: "Approved",
  },
  {
    id: 7,
    name: "George Miller",
    email: "george@example.com",
    role: "Data Scientist",
    experience: "3 years",
    status: "Pending",
  },
  {
    id: 8,
    name: "Hannah White",
    email: "hannah@example.com",
    role: "Full Stack Developer",
    experience: "4 years",
    status: "Scheduled",
  },
];
